'use client';

import React, { useState } from 'react';
import { useRouter } from 'next/navigation';
import ChapterUpload from '@/components/ChapterUpload';

export default function AddChapterExample() {
  const router = useRouter();
  const [message, setMessage] = useState<{ type: 'success' | 'error'; text: string } | null>(null);

  // Example series ID - in a real app this would come from the route or context
  const seriesId = 'series_1758388822105_txzdciqg6';

  const handleUploadComplete = (result: { success: boolean; chapterId?: string; webPath?: string; error?: string }) => {
    if (result.success) {
      setMessage({
        type: 'success',
        text: `Chapter uploaded successfully! Chapter ID: ${result.chapterId}`,
      });

      // Redirect to the series page after a short delay
      setTimeout(() => {
        router.push('/library');
      }, 2000);
    } else {
      setMessage({
        type: 'error',
        text: result.error || 'Upload failed',
      });
    }
  };

  return (
    <div className="min-h-screen bg-gray-100 dark:bg-gray-900 p-8">
      <div className="max-w-3xl mx-auto bg-white dark:bg-gray-800 rounded-lg shadow-md p-6 space-y-6">
        <header className="space-y-2">
          <h1 className="text-3xl font-bold text-gray-900 dark:text-white">Add New Mokuro Chapter</h1>
          <p className="text-gray-600 dark:text-gray-400">
            This example demonstrates the host-mounted import workflow. Ensure your mokuro export lives under
            <code className="mx-1 rounded bg-gray-200 px-1 py-0.5 text-xs text-gray-700">/host-data/manga-library</code>
            inside the Docker container before importing.
          </p>
        </header>

        {message && (
          <div
            className={`p-4 rounded-md border ${
              message.type === 'success'
                ? 'bg-green-50 border-green-200 text-green-800 dark:bg-green-900/20 dark:border-green-700 dark:text-green-200'
                : 'bg-red-50 border-red-200 text-red-800 dark:bg-red-900/20 dark:border-red-700 dark:text-red-200'
            }`}
          >
            {message.text}
          </div>
        )}

        <ChapterUpload
          seriesId={seriesId}
          onUploadComplete={handleUploadComplete}
        />

        <section className="rounded-md bg-gray-50 dark:bg-gray-700/40 p-4 text-sm text-gray-700 dark:text-gray-300 space-y-2">
          <h2 className="text-sm font-semibold text-gray-900 dark:text-white">Quick tips</h2>
          <ul className="list-disc list-inside space-y-1">
            <li>Select the <code className="bg-gray-200 px-1 py-0.5 text-xs text-gray-700">.html</code> file generated by Mokuro; the importer copies matching assets automatically.</li>
            <li>If no chapter number is provided, chapter 1 is assumed.</li>
            <li>You can revisit the chapter later under the series detail page once the import completes.</li>
          </ul>
        </section>
      </div>
    </div>
  );
}
